### ISSUE TITLE
Out of service station cause issue

### ISSUE THREAD

**Issue by sturgeon86** [happydev-ca/evduty-home-assistant#1]
I got 2 EV Duty at home, one of them recently got an issue with wifi connection and shows offline in app.
After putting in my credentials I get an error Failed Setup, Will Retry and tooltips says :
'outOfService' is not a valid ChargingStatus

**Comment by sturgeon86** [comment]
I am not a Python programmer but my guess would be the enum  ChargingStatus coming from the api.
Will look later tonight.

> class ChargingStateSensor(EVDutyTerminalDevice, SensorEntity):
    _attr_device_class = SensorDeviceClass.ENUM
    _attr_options = ['Available', 'Charging']

    def __init__(self, coordinator: EVDutyCoordinator, terminal: Terminal) -> None:
        super().__init__(coordinator, terminal, 'State')

    @property
    def native_value(self):
        if self._terminal.status == ChargingStatus.in_use:
            return 'Charging'
        return 'Available'

**Comment by francoisperron** [comment]
Thanks for the PR!
