### ISSUE TITLE
Desactivatio  de la borne lors de pointes hivernales hydro Québec 

### ISSUE THREAD

**Issue by PabloQc452** [happydev-ca/evduty-home-assistant#3]
Avant tout je te félicite pour ton intégration. Crois-tu qu'il serait possible d'ajouter un interrupteur pour désactiver la borne lors des pointes hivernales Hydro-Québec?

**Comment by francoisperron** [comment]
Il est possible de configurer le nombre d'ampère maximum par l'app mobile.
Je regarde cette semaine pour ajouter cette fonctionnalité à l'intégration.

**Comment by francoisperron** [comment]
Fonctionnalité ajoutée dans la version 0.3.0.

Merci pour la suggestion :)

<img width="1487" alt="test" src="https://github.com/user-attachments/assets/02b287d4-e6cc-438f-b65d-5e165683738c">

**Comment by PabloQc452** [comment]
C'est super, mais crois-tu qu'il serait possible d'y ajouter une interrupteur pour démarrer la charge directement par HA afin d'éviter d'avoir à ouvrir l'app Evduty et cliquer sur demarrer comme sur l'image?
![Screenshot_20240907_154526_EVDuty](https://github.com/user-attachments/assets/461dfa1d-84a4-4c7f-8fd0-746176f33385)

**Comment by francoisperron** [comment]
Je ne connais pas le call que l'app mobile fait au backend de EVDuty pour démarrer la charge.

Par contre, dans la configuration de ta borne dans l'application EVDuty, tu peux choisir "Instant charge" au-lieu de "Access control" pour que la charge débute dès que tu branches une auto. 

Puis si le Max Amp est à 0, ça ne chargera pas, si tu le mets au Max (30 ou 40), ça va charger au max.
