### ISSUE TITLE
Error when changing Max Amp: Failed to perform the action number/set_value. unknown error

### ISSUE THREAD

**Issue by end2endzone** [happydev-ca/evduty-home-assistant#4]
Premièrement, bravo et merci pour l'intégration. C'est formidable de faire un nouvelle acquisition de hardware et de voir que quelqu'un a prit la peine de penser à faire une intégration pour Home Assistant.

J'ai vu dans d'autres issues que l'utilisation attendue était de changer le `Max Amp` de 0 à whatever pour simuler le bouton de charge de l'application. Ça nécessite par contre de setté le Access Mode de la borne à `Reports` pour avoir un "instant charge" au lieu de le garder en "Access control and reports". Cela dit, j'aimerais bien moi aussi avoir un bouton on/off plutôt que de setter à 0 à 20. Pour le workaround, j'ai besoin de me setter un Helper texte qui contient ma valeur de max amp à 20 et puis quand je set le on/off, je prend la valeur du helper pour setter le Max Amp de ton intégration. Anyway, moving on... 

Il semble qu'il y ait un problème du côté de l'intégration quand on veut changer le Max Amp. Si je le change, j'ai le message suivant qui s'affiche dans le dashboard de HA:
`Failed to perform the action number/set_value. unknown error`.

Le call ne fonctionne pas. Si je veux le changer à 33, l'application ne montre pas le changement.

Si je vais dans les logs à http://homeassistant.local:8123/config/logs, je vois une entrée pour cette l'intégration spécifique:
[home-assistant_2024-11-20T21-37-46.025Z.log](https://github.com/user-attachments/files/17837073/home-assistant_2024-11-20T21-37-46.025Z.log)

Un peu plus de contexte et d'info:
* Dans l'application, j'ai activé le bouton "Power limitation". J'avais peur que setté un max amp avec un "power limitation" à off soit le problème mais non.
* Je sais que ce n'est pas un problème de username/password. J'ai validé que le REST API fonctionne bien en mode GET. J'ai setté le Power Limitation à "ON" et j'ai appliqué une Limit à 39A avec l'application Android. Je vois bien la valeur `39` dans le GUI de HA.
* Ma VM de Home Assistant est à jour:
  * Core 2024.11.2
  * Supervisor 2024.11.2
  * Operating System 13.2
  * Frontend 20241106.2

Je ne suis pas un développeur python et j'ai un peu de misère à suivre le code avec les nombreux points d'entrées et callback asynchrones mais je peux fournir de l'aide pour reproduire ou tester un fix.

**Comment by Fetochini** [comment]
Oui c'est vrai que c'est génial d'avoir finalement une intégration à home assistant. Lorsque je l'ai installé j'ai aussi eu la même erreur que toi. De mémoire j'ai reboot home assistant et reloger l'application evduty dans mon téléphone.

**Comment by end2endzone** [comment]
Salut.

Malheureusement, ça ne semble pas fonctionner. J'avais déjà fait un reboot de HA tel qu'[indiqué dans les instructions après avoir fait le download](https://github.com/happydev-ca/evduty-home-assistant/blob/0.3.0/README.md?plain=1#L20). J'ai refais un reboot aujourd'hui ainsi qu'un _Sign Out_ puis _Log In_ dans l'application android. Le tout dans cet ordre. J'ai toujours le même message d'erreur.

Je suis encore nouveau avec HACS alors c'est possible que j'ai fait une erreur.

À noter que je n'ai pas réussi à installer avec les instructions "Or" du README ([section Automatic, Or](https://github.com/happydev-ca/evduty-home-assistant/blob/0.3.0/README.md?plain=1#L16)). De mon point de vue, cette intégration ne semble pas faire partie des intégrations disponible "par default" via HACS. J'ai du passé par le lien https://my.home-assistant.io/redirect/hacs_repository/?owner=happydev-ca&repository=evduty-home-assistant&category=integration qui a ajouter ce repository git en tant que repo de HACS. Ensuite j'ai pu retrouvé l'intégration en filtrant pour `EVduty`.

Je vais essayer de voir si je peux aussi reproduire le problème avec `evduty-api` pour savoir si c'est un problème que j'ai avec la lib ou avec l'intégration. Si c'est le cas, je vais probablement ouvrir un issue pour la librairie au lieu de l'intégration. À suivre.

**Comment by francoisperron** [comment]
Salut!

Merci pour les logs! On y voit que le PUT pour mettre à jour le terminal a retourné un BAD_REQUEST.
`File "/usr/local/lib/python3.12/site-packages/evdutyapi/evduty_api.py", line 86, in async_set_terminal_max_charging_current
    await self._raise_on_get_error(put_response)
 File "/usr/local/lib/python3.12/site-packages/evdutyapi/evduty_api.py", line 94, in _raise_on_get_error
    raise EVDutyApiError(response.request_info, response.history, status=response.status, message=response.reason, headers=response.headers)
evdutyapi.evduty_api.EVDutyApiError: 400, message='Bad Request'`

L'API de EVduty est capricieux. Pour changer une seule valeur (chargingRate), on doit faire un GET du terminal, enlever les valeurs non modifiables, puis faire un PUT avec ce qui reste en changeant la valeur du chargingRate.

Je vais faire quelques tests et faire une version où les requests et responses seront loggées en debug. Ça va aider à trouver l'erreur.

ps. L'intégration n'est effectivement pas encore disponible par défaut dans HASC, la PR dans HACS est ouverte depuis février 2024 et il y a 343 PR à faire!
https://github.com/hacs/default/pull/2371

**Comment by francoisperron** [comment]
@end2endzone Dans l'app EVduty, peux-tu essayer de mettre la switch "Show estimated electricity cost" active, et saisir un "Cost per Kw-hr", puis réessayer de changer l'amperage dans HA?

**Comment by end2endzone** [comment]
@francoisperron  Oh yes! Tu as vu juste. Ça fonctionne à merveille!

Si j'ai bien compris, le problème c'est que la lib ajoute le flag (ou la valeur) concernant le coût de l'électricité dans le PUT. La lib assume probablement que c'est une "valeur modifiable". Et puisque mon flag était à OFF, l'API de EVduty retourne une erreur.

Je suis nouvellement propriétaire d'une borne. Je n'ai pas changé le flag. EVduty met donc le flag à OFF avec l'activation des nouveaux comptes.

S'il existe un moyen de savoir si le flag est à _ON_ ou _OFF_ en faisant un GET, je crois que meilleure solution serait de fixer la librairie pour bien gérer le PUT. Dans ce cas, je crois que le problème est dans la lib et non pas dans l'intégration. Comment est-ce que tu veux adresser la suite des choses?
1. Est-ce que tu veux que j'ouvre un issue contre la lib? (pour éventuellement fermer cette issue ci).
2. Garder cet issue ouvert jusqu'à ce qu'il y ait un fix dans `evduty-api` ?
3. Ajouter une section "Troubleshooting" ou "Notes" dans le README de l'intégration. Dans la nouvelle section, on ajoute une note qui dit que c'est obligatoire d'avoir le flag "Show estimated electricity cost" à ON. C'est la solution la plus simple et rapide à mon avis.

Je suis aussi ouvert à simplement fermer l'issue. Je ne veux pas mettre de pression. Je sais ce que c'est d'avoir des users qui font des demandes pour leur propre besoin. Et c'est parfois compliquer de mettre du temps dans un projet du type hobby. Par contre, je crois que c'est bien possible qu'un autre usagé expérimente le même problème. Je crois en l'importance de faciliter le processus d'intégration le plus possible afin de maximiser l'expérience HA.

> Je vais faire quelques tests et faire une version où les requests et responses seront loggées en debug. Ça va aider à trouver l'erreur.

Je seconde. Ça serait effectivement utile pour les autres devs pour comprendre les futurs problèmes. Je suis complètement nouveau concernant le dévelopement et le debuggage d'intégration. Je suis habituellement user. Je crois que j'ai été mélangé avec le commentaire _This custom integration does not support configuration through the configuration.yaml file_ et la section [Debug du README](https://github.com/happydev-ca/evduty-home-assistant?tab=readme-ov-file#debug). Peut-être que si j'avais activé le mode debug pour l'intégration, j'aurais peut-être été plus capable de fournir des indices sur le problème.

**Comment by francoisperron** [comment]
@end2endzone 

C'est déjà [fixé](https://github.com/happydev-ca/evduty-api/commit/9bccb40e2f8023dbf69a89916216506e4f180599
) dans l'api, si ya une valeur ça la garde, sinon ça enlève le champs.

Dispo dans la version [0.3.1](https://github.com/happydev-ca/evduty-home-assistant/releases/tag/0.3.1) de l'intégration.

La section Debug est nouvelle [d'hier](https://github.com/happydev-ca/evduty-home-assistant/commit/f7f15dd295baa5b32cb5e290a4a92a752fd7bd74). J'ai modifié le readme pour prendre en compte ton commentaire :)
